### ISSUE TITLE
ReferenceError: "cordova is not defined"

### ISSUE THREAD

**Issue by mjrc** [aaronksaunders/capacitor-vue-ionicv4-app#6]
Hi there. Thanks for submitting this example. I've cloned your project and installed the dependancies according to the instructions but I've to the issue that cordova is not defined on `src/components/CameraPage.vue` at line 37. After installing and importing `cordova` in the projects it tells me it is also missing the `readline` and `module` package. After installing those, it returns the following module was not found:  `* ./defaults.json in ./node_modules/cordova-lib/src/plugman/init-defaults.js`

Does the barcode scanner work? I'm feeling like I'm overlooking something quite simple here. Could you comment on what might be going on?

**Comment by aaronksaunders** [comment]
this was built to run on device...

**Comment by aaronksaunders** [comment]
tested and works
